/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GridDialog.java
 *
 * Created on Jul 30, 2010, 3:56:25 PM
 */

package com.frederickw.canvas.ui;

import java.awt.Color;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.LayoutStyle;
import javax.swing.SpinnerNumberModel;

/**
 * 
 * @author Frederick
 */
public class GridDialog extends JDialog {

	private static final long serialVersionUID = -9188847595489610621L;

	private ColorChooserDialog colorChooser;

	public GridDialog(java.awt.Frame parent, boolean modal,
			ColorChooserDialog colorChooser) {
		super(parent, modal);
		this.colorChooser = colorChooser;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		cellWidth = new JSpinner();
		jLabel1 = new JLabel();
		jLabel2 = new JLabel();
		jLabel3 = new JLabel();
		cellHeight = new JSpinner();
		jLabel4 = new JLabel();
		gridColorPanel = new JPanel();

		setTitle("Grid Options");

		cellWidth.setModel(new SpinnerNumberModel(Integer.valueOf(25), Integer
				.valueOf(1), null, Integer.valueOf(1)));

		jLabel1.setText("Grid Options:");

		jLabel2.setText("Cell Width:");

		jLabel3.setText("Cell Height:");

		cellHeight.setModel(new SpinnerNumberModel(Integer.valueOf(25), Integer
				.valueOf(1), null, Integer.valueOf(1)));

		jLabel4.setText("Color:");

		gridColorPanel.setBackground(new Color(255, 0, 0, 150));
		gridColorPanel.setBorder(BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));
		gridColorPanel.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				gridColorPanelMouseReleased(evt);
			}
		});

		GroupLayout gridColorPanelLayout = new GroupLayout(gridColorPanel);
		gridColorPanel.setLayout(gridColorPanelLayout);
		gridColorPanelLayout.setHorizontalGroup(gridColorPanelLayout
				.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0,
						25, Short.MAX_VALUE));
		gridColorPanelLayout.setVerticalGroup(gridColorPanelLayout
				.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0,
						25, Short.MAX_VALUE));

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(10, 10,
																		10)
																.addComponent(
																		jLabel2)
																.addPreferredGap(
																		LayoutStyle.ComponentPlacement.RELATED,
																		91,
																		Short.MAX_VALUE)
																.addComponent(
																		cellWidth,
																		GroupLayout.PREFERRED_SIZE,
																		80,
																		GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(10, 10,
																		10)
																.addGroup(
																		layout.createParallelGroup(
																				GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel4)
																								.addPreferredGap(
																										LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										gridColorPanel,
																										GroupLayout.PREFERRED_SIZE,
																										GroupLayout.DEFAULT_SIZE,
																										GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel3)
																								.addPreferredGap(
																										LayoutStyle.ComponentPlacement.RELATED,
																										88,
																										Short.MAX_VALUE)
																								.addComponent(
																										cellHeight,
																										GroupLayout.PREFERRED_SIZE,
																										80,
																										GroupLayout.PREFERRED_SIZE)))))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(7, 7, 7)
								.addComponent(jLabel1)
								.addPreferredGap(
										LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														cellWidth,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														cellHeight,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												GroupLayout.Alignment.LEADING)
												.addComponent(jLabel4)
												.addComponent(
														gridColorPanel,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE))
								.addContainerGap(GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void gridColorPanelMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_gridColorPanelMouseReleased
		colorChooser.setTarget(gridColorPanel);
		colorChooser.setVisible(true);
	}// GEN-LAST:event_gridColorPanelMouseReleased

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public JSpinner cellHeight;
	public JSpinner cellWidth;
	public JPanel gridColorPanel;
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JLabel jLabel3;
	private JLabel jLabel4;
	// End of variables declaration//GEN-END:variables

}
