/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RRDialog.java
 *
 * Created on Jul 30, 2010, 5:02:58 PM
 */

package com.frederickw.canvas.ui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.GroupLayout;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.LayoutStyle;
import javax.swing.SpinnerNumberModel;

/**
 * 
 * @author Frederick
 */
public class RRDialog extends JDialog {

	private static final long serialVersionUID = -7901202926869202758L;

	/** Creates new form RRDialog */
	public RRDialog(ToolboxFrame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new JLabel();
		jLabel2 = new JLabel();
		arcWidth = new JSpinner();
		jLabel3 = new JLabel();
		jLabel4 = new JLabel();
		arcHeight = new JSpinner();

		setTitle("Rounded Rectangle");
		addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		jLabel1.setText("Rounded Rectangle options:");

		jLabel2.setText("Arc Width:");

		arcWidth.setModel(new SpinnerNumberModel(Integer.valueOf(16), Integer
				.valueOf(0), null, Integer.valueOf(1)));

		jLabel3.setText("Arc Height:");

		jLabel4.setText("<html>These values change how large the rounded<br>\nrectangle's edges will be, in pixels.");

		arcHeight.setModel(new SpinnerNumberModel(Integer.valueOf(16), Integer
				.valueOf(0), null, Integer.valueOf(1)));

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(10, 10,
																		10)
																.addGroup(
																		layout.createParallelGroup(
																				GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jLabel2))
																.addPreferredGap(
																		LayoutStyle.ComponentPlacement.RELATED,
																		73,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				GroupLayout.Alignment.TRAILING,
																				false)
																				.addComponent(
																						arcHeight)
																				.addComponent(
																						arcWidth,
																						GroupLayout.DEFAULT_SIZE,
																						76,
																						Short.MAX_VALUE)))
												.addComponent(
														jLabel4,
														GroupLayout.Alignment.TRAILING))
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel1)
						.addGap(6, 6, 6)
						.addGroup(
								layout.createParallelGroup(
										GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel2)
										.addComponent(arcWidth,
												GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(
								LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(
								layout.createParallelGroup(
										GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3)
										.addComponent(arcHeight,
												GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(
								LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jLabel4)
						.addContainerGap(GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowClosing(WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
		((ToolboxFrame) getParent()).roundRectDialogClosed();
	}// GEN-LAST:event_formWindowClosing

	// Variables declaration - do not modify//GEN-BEGIN:variables
	public JSpinner arcHeight;
	public JSpinner arcWidth;
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JLabel jLabel3;
	private JLabel jLabel4;
	// End of variables declaration//GEN-END:variables

}
